version: "3.9"
services:
  backend:
    container_name: back-task-manager-app
    restart: always
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
